"""The SSH include dck generates for Herdr machines: ~/.ssh/config.d/dck.

One file, one `Host <alias>` block per repository, each between
`# >>> dck:<alias> >>>` / `# <<< dck:<alias> <<<`. The file starts with a
provenance header; the writer refuses to touch a file without it (it would
be someone else's). Every block connects to the container's loopback port
with the dedicated dck key only, forwards the agent (the developer's own keys
never enter the container), and keeps host keys in dck's own known_hosts so
~/.ssh/known_hosts never grows a line per container.

~/.ssh/config gets one `Include config.d/dck` line at the top (OpenSSH only
applies an Include placed before the first Host block to every host).
"""

import os
import re

PROVENANCE = "# dck-provenance: v1"
HEADER = [
    "# Generated by devcontainer-kit (dck). Do not edit: `dck herdr add|remove`",
    "# rewrite the blocks below. Remove a repository with `dck herdr remove`.",
    PROVENANCE,
]
INCLUDE_MARK = "# Added by devcontainer-kit (dck): Herdr machine aliases"
RE_ALIAS = r"^[a-z0-9][a-z0-9._-]{0,63}$"
RE_HOST = r"^[0-9.]+$|^localhost$"
RE_USER = r"^[a-z_][a-z0-9_-]{0,31}$"


class SshConfError(Exception):
    def __init__(self, msg, code=3):
        super().__init__(msg)
        self.code = code


def _check_path_value(name, value):
    if not value or any(c in value for c in '\n\r"') or value != value.strip():
        raise SshConfError("invalid %s: %r" % (name, value))


def block(alias, host, port, user, identity, known_hosts):
    if not re.match(RE_ALIAS, alias):
        raise SshConfError("invalid alias %r" % alias)
    if not re.match(RE_HOST, host):
        raise SshConfError("invalid host %r" % host)
    if not re.match(RE_USER, user):
        raise SshConfError("invalid user %r" % user)
    port = int(port)
    if not 1 <= port <= 65535:
        raise SshConfError("invalid port %r" % port)
    _check_path_value("identity", identity)
    _check_path_value("known_hosts", known_hosts)
    return [
        "# >>> dck:%s >>>" % alias,
        "Host %s" % alias,
        "  HostName %s" % host,
        "  Port %d" % port,
        "  User %s" % user,
        '  IdentityFile "%s"' % identity,
        "  IdentitiesOnly yes",
        "  ForwardAgent yes",
        "  StrictHostKeyChecking accept-new",
        "  HostKeyAlias %s" % alias,
        '  UserKnownHostsFile "%s"' % known_hosts,
        "  ServerAliveInterval 30",
        "# <<< dck:%s <<<" % alias,
    ]


def _read_owned(path):
    """Lines of an existing include that carries our provenance, [] when absent."""
    if os.path.islink(path):
        raise SshConfError("%s is a symlink; refusing to write through it" % path, 5)
    if not os.path.exists(path):
        return []
    lines = open(path).read().splitlines()
    if PROVENANCE not in lines[:5]:
        raise SshConfError("%s exists without the dck provenance header; refusing to "
                           "overwrite a file dck did not write" % path, 5)
    return lines


def _blocks(lines):
    """[(alias, start, end)] of the managed blocks; raises on broken markers."""
    out, open_alias, start = [], None, None
    for i, ln in enumerate(lines):
        m = re.match(r"^# (>>>|<<<) dck:(\S+) (>>>|<<<)$", ln)
        if not m:
            continue
        if m.group(1) == ">>>":
            if open_alias is not None:
                raise SshConfError("unbalanced dck markers in the include", 5)
            open_alias, start = m.group(2), i
        else:
            if open_alias != m.group(2):
                raise SshConfError("unbalanced dck markers in the include", 5)
            out.append((open_alias, start, i))
            open_alias = None
    if open_alias is not None:
        raise SshConfError("unbalanced dck markers in the include", 5)
    return out


def _write(path, lines):
    d = os.path.dirname(path)
    os.makedirs(d, mode=0o700, exist_ok=True)
    tmp = "%s.tmp-%d" % (path, os.getpid())
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600)
    with os.fdopen(fd, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    os.replace(tmp, path)


def upsert(path, alias, host, port, user, identity, known_hosts):
    """Add or replace the block for `alias`. Returns 'added', 'updated' or 'unchanged'."""
    lines = _read_owned(path)
    new_block = block(alias, host, port, user, identity, known_hosts)
    if not lines:
        _write(path, HEADER + [""] + new_block)
        return "added"
    for a, s, e in _blocks(lines):
        if a == alias:
            if lines[s:e + 1] == new_block:
                return "unchanged"
            _write(path, lines[:s] + new_block + lines[e + 1:])
            return "updated"
    while lines and not lines[-1].strip():
        lines.pop()
    _write(path, lines + [""] + new_block)
    return "added"


def remove(path, alias):
    """Remove the block for `alias`. Returns 'removed' or 'absent'."""
    lines = _read_owned(path)
    for a, s, e in _blocks(lines):
        if a == alias:
            rest = lines[:s] + lines[e + 1:]
            # collapse the blank line left behind
            out = []
            for ln in rest:
                if not ln.strip() and out and not out[-1].strip():
                    continue
                out.append(ln)
            while out and not out[-1].strip():
                out.pop()
            _write(path, out)
            return "removed"
    return "absent"


def has_alias(path, alias):
    try:
        return any(a == alias for a, _, _ in _blocks(_read_owned(path)))
    except SshConfError:
        return False


def ensure_include(config_path, include="config.d/dck"):
    """Put `Include <include>` at the top of ~/.ssh/config. Returns 'added' or 'present'."""
    line = "Include %s" % include
    if os.path.islink(config_path):
        target = os.path.realpath(config_path)
        if not os.path.isfile(target):
            raise SshConfError("%s is a dangling symlink" % config_path, 5)
        config_path = target
    existing = open(config_path).read() if os.path.exists(config_path) else ""
    for ln in existing.splitlines():
        if ln.strip() == line:
            return "present"
    os.makedirs(os.path.dirname(config_path), mode=0o700, exist_ok=True)
    mode = os.stat(config_path).st_mode & 0o777 if os.path.exists(config_path) else 0o600
    new = "%s\n%s\n\n%s" % (INCLUDE_MARK, line, existing) if existing else "%s\n%s\n" % (INCLUDE_MARK, line)
    tmp = "%s.tmp-%d" % (config_path, os.getpid())
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, mode)
    with os.fdopen(fd, "w") as fh:
        fh.write(new)
    os.replace(tmp, config_path)
    return "added"
