"""The SSH include dck generates for Herdr machines: ~/.ssh/config.d/dck.

One file, one `Host <alias>` block per repository, each between
`# >>> dck:<alias> >>>` / `# <<< dck:<alias> <<<`. The file starts with a
provenance header; the writer refuses to touch a file without it (it would
be someone else's). Every block connects to the container's loopback port
with the dedicated dck key only, forwards the agent (the developer's own keys
never enter the container), and keeps host keys in dck's own known_hosts so
~/.ssh/known_hosts never grows a line per container.

~/.ssh/config gets one `Include config.d/dck` line at the top (OpenSSH only
applies an Include placed before the first Host block to every host).
"""

import os
import re

PROVENANCE = "# dck-provenance: v1"
HEADER = [
    "# Generated by devcontainer-kit (dck). Do not edit: `dck herdr add|remove`",
    "# rewrite the blocks below. Remove a repository with `dck herdr remove`.",
    PROVENANCE,
]
INCLUDE_MARK = "# Added by devcontainer-kit (dck): Herdr machine aliases"
RE_ALIAS = r"^[a-z0-9][a-z0-9._-]{0,63}$"
RE_HOST = r"^127\.0\.0\.1$"  # agent forwarding never leaves this machine
RE_USER = r"^[a-z_][a-z0-9_-]{0,31}$"


class SshConfError(Exception):
    def __init__(self, msg, code=3):
        super().__init__(msg)
        self.code = code


def _check_path_value(name, value):
    if not value or any(c in value for c in '\n\r"') or value != value.strip():
        raise SshConfError("invalid %s: %r" % (name, value))


def block(alias, host, port, user, identity, known_hosts):
    if not re.match(RE_ALIAS, alias):
        raise SshConfError("invalid alias %r" % alias)
    if not re.match(RE_HOST, host):
        raise SshConfError("invalid host %r" % host)
    if not re.match(RE_USER, user):
        raise SshConfError("invalid user %r" % user)
    port = int(port)
    if not 1 <= port <= 65535:
        raise SshConfError("invalid port %r" % port)
    _check_path_value("identity", identity)
    _check_path_value("known_hosts", known_hosts)
    return [
        "# >>> dck:%s >>>" % alias,
        "Host %s" % alias,
        "  HostName %s" % host,
        "  Port %d" % port,
        "  User %s" % user,
        '  IdentityFile "%s"' % identity,
        "  IdentitiesOnly yes",
        "  ForwardAgent yes",
        "  StrictHostKeyChecking accept-new",
        "  HostKeyAlias %s" % alias,
        '  UserKnownHostsFile "%s"' % known_hosts,
        "  ServerAliveInterval 30",
        "# <<< dck:%s <<<" % alias,
    ]


def _read_owned(path):
    """Lines of an existing include that carries our provenance, [] when absent."""
    if os.path.islink(path):
        raise SshConfError("%s is a symlink; refusing to write through it" % path, 5)
    if not os.path.exists(path):
        return []
    lines = open(path).read().splitlines()
    if PROVENANCE not in lines[:5]:
        raise SshConfError("%s exists without the dck provenance header; refusing to "
                           "overwrite a file dck did not write" % path, 5)
    return lines


def _blocks(lines):
    """[(alias, start, end)] of the managed blocks; raises on broken markers."""
    out, open_alias, start = [], None, None
    for i, ln in enumerate(lines):
        m = re.match(r"^# (>>>|<<<) dck:(\S+) (>>>|<<<)$", ln)
        if not m:
            continue
        if m.group(1) == ">>>":
            if open_alias is not None:
                raise SshConfError("unbalanced dck markers in the include", 5)
            open_alias, start = m.group(2), i
        else:
            if open_alias != m.group(2):
                raise SshConfError("unbalanced dck markers in the include", 5)
            out.append((open_alias, start, i))
            open_alias = None
    if open_alias is not None:
        raise SshConfError("unbalanced dck markers in the include", 5)
    return out


def _write(path, lines):
    d = os.path.dirname(path)
    os.makedirs(d, mode=0o700, exist_ok=True)
    tmp = "%s.tmp-%d" % (path, os.getpid())
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600)
    with os.fdopen(fd, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    os.replace(tmp, path)


def upsert(path, alias, host, port, user, identity, known_hosts):
    """Add or replace the block for `alias`. Returns 'added', 'updated' or 'unchanged'."""
    lines = _read_owned(path)
    new_block = block(alias, host, port, user, identity, known_hosts)
    if not lines:
        _write(path, HEADER + [""] + new_block)
        return "added"
    for a, s, e in _blocks(lines):
        if a == alias:
            if lines[s:e + 1] == new_block:
                return "unchanged"
            _write(path, lines[:s] + new_block + lines[e + 1:])
            return "updated"
    while lines and not lines[-1].strip():
        lines.pop()
    _write(path, lines + [""] + new_block)
    return "added"


def remove(path, alias):
    """Remove the block for `alias`. Returns 'removed' or 'absent'."""
    lines = _read_owned(path)
    for a, s, e in _blocks(lines):
        if a == alias:
            rest = lines[:s] + lines[e + 1:]
            # collapse the blank line left behind
            out = []
            for ln in rest:
                if not ln.strip() and out and not out[-1].strip():
                    continue
                out.append(ln)
            while out and not out[-1].strip():
                out.pop()
            _write(path, out)
            return "removed"
    return "absent"


def has_alias(path, alias):
    try:
        return any(a == alias for a, _, _ in _blocks(_read_owned(path)))
    except SshConfError:
        return False


# A user name dck accepts on both sides of the mesh (lib/entrypoint.sh
# dck_mesh_apply uses the same class).
USER_RE = r"[a-z_][a-z0-9_.-]*"


def _hashed_match(field, name):
    """True when `field` is an OpenSSH hashed host (|1|salt|hash) of `name`."""
    import base64
    import hashlib
    import hmac
    try:
        _, kind, salt, digest = field.split("|")
        if kind != "1":
            return False
        mac = hmac.new(base64.b64decode(salt), name.encode(), hashlib.sha1).digest()
        return hmac.compare_digest(mac, base64.b64decode(digest))
    except (ValueError, TypeError):
        return False


def _known_port(hosts, by_alias, ports):
    """The peer port a known_hosts host field belongs to, or None."""
    for host in hosts.split(","):
        if host.startswith("|1|"):
            for alias, port in by_alias.items():
                if _hashed_match(host, alias):
                    return port
            continue
        if host in by_alias:
            return by_alias[host]
        m = re.match(r"^\[127\.0\.0\.1\]:(\d+)$", host)
        if m and m.group(1) in ports:
            return m.group(1)
    return None


def peers(path, known_hosts, exclude="", labels=None, host_user="", host_key_file=""):
    """The mesh payload `dck_mesh_apply` reads inside a container: one
    `peer <alias> <port> <user> <label>` line per managed block of the include
    except `exclude`, one `hostkey <port> <type> <key>` line per pinned host key
    of those peers (from dck's known_hosts: entries for the alias — dck pins
    with HostKeyAlias — plain or hashed, or legacy `[127.0.0.1]:<port>`), and,
    when host_user is set, the host itself (`dck-host`, port 22) with its own
    host key. Public data only: aliases, ports, users, labels, public keys."""
    labels = labels or {}
    lines = _read_owned(path) if os.path.exists(path) else []
    out, ports, by_alias = [], set(), {}
    for alias, start, end in _blocks(lines):
        if alias == exclude:
            continue
        port = user = None
        for ln in lines[start:end]:
            m = re.match(r"^\s+Port\s+(\d+)\s*$", ln)
            if m:
                port = m.group(1)
            m = re.match(r"^\s+User\s+(%s)\s*$" % USER_RE, ln)
            if m:
                user = m.group(1)
        if port and user:
            out.append("peer %s %s %s %s" % (alias, port, user, labels.get(alias, alias)))
            ports.add(port)
            by_alias[alias] = port
    if known_hosts and os.path.exists(known_hosts):
        seen = set()
        with open(known_hosts) as fh:
            for ln in fh:
                parts = ln.split()
                if len(parts) < 3 or parts[0].startswith(("#", "@")):
                    continue
                port = _known_port(parts[0], by_alias, ports)
                if not port or not re.match(r"^[A-Za-z0-9+/=]+$", parts[2]):
                    continue
                entry = "hostkey %s %s %s" % (port, parts[1], parts[2])
                if entry not in seen:
                    seen.add(entry)
                    out.append(entry)
    if host_user:
        if not re.match(r"^%s$" % USER_RE, host_user):
            raise SshConfError("invalid host user %r" % host_user, 2)
        out.append("peer dck-host 22 %s %s" % (host_user, labels.get("dck-host", "host")))
        if host_key_file and os.path.exists(host_key_file):
            parts = open(host_key_file).read().split()
            if len(parts) >= 2:
                out.append("hostkey 22 %s %s" % (parts[0], parts[1]))
    return "\n".join(out) + ("\n" if out else "")


def ensure_include(config_path, include="config.d/dck"):
    """Put `Include <include>` at the top of ~/.ssh/config. Returns 'added' or 'present'."""
    line = "Include %s" % include
    if os.path.islink(config_path):
        target = os.path.realpath(config_path)
        if not os.path.isfile(target):
            raise SshConfError("%s is a dangling symlink" % config_path, 5)
        config_path = target
    existing = open(config_path).read() if os.path.exists(config_path) else ""
    for ln in existing.splitlines():
        if ln.strip() == line:
            return "present"
    os.makedirs(os.path.dirname(config_path), mode=0o700, exist_ok=True)
    mode = os.stat(config_path).st_mode & 0o777 if os.path.exists(config_path) else 0o600
    new = "%s\n%s\n\n%s" % (INCLUDE_MARK, line, existing) if existing else "%s\n%s\n" % (INCLUDE_MARK, line)
    tmp = "%s.tmp-%d" % (config_path, os.getpid())
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, mode)
    with os.fdopen(fd, "w") as fh:
        fh.write(new)
    os.replace(tmp, config_path)
    return "added"


# --- the developer's own SSH aliases, public halves only -------------------------
# `dck up` makes the host's `Host` aliases (github.com-work, …) usable inside the
# container: each concrete alias with its HostName/Port/User and the PUBLIC half of
# its IdentityFile, so OpenSSH inside asks the host agent for exactly that key. No
# private key, no ProxyCommand/ProxyJump (they run commands or need other hosts),
# no loopback alias (those are machines on the host), no dck-managed alias.

HOSTID_ALIAS = r"^[A-Za-z0-9_][A-Za-z0-9._-]{0,127}$"
HOSTID_NAME = r"^[A-Za-z0-9][A-Za-z0-9.-]{0,252}$"
HOSTID_USER = r"^[A-Za-z0-9_][A-Za-z0-9._-]{0,63}$"
HOSTID_KEY = r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$"
KEY_TYPES = ("ssh-ed25519", "ssh-rsa", "ecdsa-sha2-nistp256", "ecdsa-sha2-nistp384",
             "ecdsa-sha2-nistp521", "sk-ssh-ed25519@openssh.com",
             "sk-ecdsa-sha2-nistp256@openssh.com")
# Git hosting services: their aliases are made usable inside by default. Any other
# host needs an explicit opt-in (the host profile's [ssh] host_extra), so a container never learns of —
# and the agent is never loaded with keys for — servers it has no business with.
GIT_HOSTS = ("github.com", "ssh.github.com", "gitlab.com", "altssh.gitlab.com",
             "bitbucket.org", "altssh.bitbucket.org", "ssh.dev.azure.com",
             "vs-ssh.visualstudio.com", "codeberg.org", "git.sr.ht")
_SKIP_KEYS = ("proxycommand", "proxyjump", "localcommand", "remotecommand",
              "permitlocalcommand", "knownhostscommand")


def _sshconf_lines(path, home, depth=0, seen=None):
    """The lines of an ssh config with its Include files spliced in (OpenSSH
    resolves relative Include paths against ~/.ssh). Unreadable files are skipped."""
    import glob
    seen = seen if seen is not None else set()
    real = os.path.realpath(path)
    if depth > 4 or real in seen or not os.path.isfile(real):
        return []
    seen.add(real)
    try:
        with open(real, errors="replace") as fh:
            raw = fh.read().splitlines()
    except OSError:
        return []
    out = []
    for ln in raw:
        m = re.match(r"^\s*include\s*=?\s*(.+?)\s*$", ln, re.I)
        if not m:
            out.append(ln)
            continue
        import shlex
        try:
            pats = shlex.split(m.group(1))
        except ValueError:
            pats = []
        for pat in pats:
            if pat.startswith("~/"):
                pat = os.path.join(home, pat[2:])
            elif not os.path.isabs(pat):
                pat = os.path.join(home, ".ssh", pat)
            for f in sorted(glob.glob(pat)):
                out.extend(_sshconf_lines(f, home, depth + 1, seen))
    return out


def _loopback(name):
    n = name.lower()
    return n == "localhost" or n.startswith("127.") or n in ("::1", "0.0.0.0")


def _known_for(hosts, known_hosts):
    """`kh` lines: the host keys the developer already trusts for these hosts."""
    want = {}
    for h in hosts:
        _, _, hostname, port, _, _ = h.split(" ")
        want[hostname if port == "22" else "[%s]:%s" % (hostname, port)] = (hostname, port)
    out, seen = [], set()
    try:
        lines = open(known_hosts, errors="replace").read().splitlines()
    except OSError:
        return out
    for ln in lines:
        parts = ln.split()
        if len(parts) < 3 or parts[0].startswith(("#", "@")) or parts[1] not in KEY_TYPES:
            continue
        if not re.match(r"^[A-Za-z0-9+/=]+$", parts[2]):
            continue
        for field in parts[0].split(","):
            for name, (hostname, port) in want.items():
                if field == name or (field.startswith("|1|") and _hashed_match(field, name)):
                    entry = "kh %s %s %s %s" % (hostname, port, parts[1], parts[2])
                    if entry not in seen:
                        seen.add(entry); out.append(entry)
    return out[:400]


def host_identities(config_path, home, extra=()):
    """Payload for dck_hostssh_apply (one line each):
         pub  <key> <type> <base64>
         host <alias> <hostname> <port> <user|-> <key>
         kh   <hostname> <port> <type> <base64>   (pinned host keys from ~/.ssh/known_hosts)
       plus, for the host side only (never pushed):
         file<TAB><key><TAB><public key path><TAB><private key path, or - when absent>
    """
    blocks, cur = [], None
    for ln in _sshconf_lines(config_path, home):
        s = ln.strip()
        if not s or s.startswith("#"):
            continue
        m = re.match(r"^(\S+?)\s*(?:=\s*|\s+)(.*)$", s)
        if not m:
            continue
        key, val = m.group(1).lower(), m.group(2).strip()
        if key == "host":
            cur = {"patterns": val.split(), "opts": {}}
            blocks.append(cur)
        elif key == "match":
            cur = None
        elif cur is not None and key not in cur["opts"]:
            cur["opts"][key] = val
    import hashlib
    extra = set(extra or ())
    pubs, hosts, files, names, pubpaths = {}, [], {}, {}, {}
    for b in blocks:
        o = b["opts"]
        if any(k in o for k in _SKIP_KEYS) or "identityfile" not in o:
            continue
        ident = o["identityfile"].strip('"')
        if ident.startswith("~/"):
            ident = os.path.join(home, ident[2:])
        if "%" in ident or not os.path.isabs(ident):
            continue
        pub = ident if ident.endswith(".pub") else ident + ".pub"
        if not os.path.isfile(pub):
            continue
        try:
            parts = open(pub, errors="replace").read().split()
        except OSError:
            continue
        if len(parts) < 2 or parts[0] not in KEY_TYPES or not re.match(r"^[A-Za-z0-9+/=]+$", parts[1]):
            continue
        priv = ident[:-4] if ident.endswith(".pub") else ident
        if os.path.realpath(pub) == os.path.realpath(priv):
            continue
        name = names.get(priv)
        if name is None:
            base = re.sub(r"[^A-Za-z0-9._-]", "_", os.path.basename(priv))[:48] or "key"
            if not re.match(r"^[A-Za-z0-9]", base):
                base = "k" + base
            name = base if base not in names.values() else "%s-%s" % (
                base, hashlib.sha256(priv.encode()).hexdigest()[:8])
            names[priv] = name
        port = o.get("port", "22")
        user = o.get("user", "-")
        if not re.match(r"^[0-9]{1,5}$", port) or not 1 <= int(port) <= 65535:
            continue
        if user != "-" and not re.match(HOSTID_USER, user):
            continue
        for alias in b["patterns"]:
            if any(c in alias for c in "*?!") or alias.startswith("dck-") or not re.match(HOSTID_ALIAS, alias):
                continue
            hostname = o.get("hostname", alias)
            if "%" in hostname or not re.match(HOSTID_NAME, hostname) or _loopback(hostname):
                continue
            if hostname.lower() not in GIT_HOSTS and alias not in extra and hostname not in extra:
                continue
            pubs[name] = (parts[0], parts[1])
            files[name] = priv if os.path.isfile(priv) else "-"
            pubpaths[name] = pub
            hosts.append("host %s %s %s %s %s" % (alias, hostname, port, user, name))
    out = ["pub %s %s %s" % (n, t, k) for n, (t, k) in sorted(pubs.items())]
    out += hosts[:200]
    out += _known_for(hosts[:200], os.path.join(home, ".ssh", "known_hosts"))
    # Tab-separated: key paths may contain spaces.
    out += ["file\t%s\t%s\t%s" % (n, pubpaths[n], p) for n, p in sorted(files.items())
            if not any(c in p + pubpaths[n] for c in "\n\r\t")]
    return "\n".join(out) + ("\n" if out else "")
